
services:
  backend:
    env_file:
      - .env
    image: emmartel/tft-backend
    volumes:     
      - ./shared-data:/app/shared-data      
    ports:
      - "3000:3000"
    restart: always

  frontend:
    image: emmartel/tft-frontend-prod
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

  bandage:
    image: emmartel/bandage-api
    volumes:
      - ./shared-data:/app/data
    ports:
    - "3001:3000"
    # depends_on:
    #   - backend
    restart: always